// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day45Demo.EntityFrameworkAsyncAwaitDemo.DataAccess.Models
{
    [Table("brands", Schema = "production")]
    [Index("BrandName", Name = "UQ__brands__0C0C3B581D1B7FE1", IsUnique = true)]
    public partial class Brand
    {
        public Brand()
        {
            Products = new HashSet<Product>();
        }

        [Key]
        [Column("brand_id")]
        public int BrandId { get; set; }
        [Required]
        [Column("brand_name")]
        [StringLength(255)]
        [Unicode(false)]
        public string BrandName { get; set; }

        [InverseProperty("Brand")]
        public virtual ICollection<Product> Products { get; set; }
    }
}